services:
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: event_driven_order_system
    ports:
      - "5433:5432"
    volumes:
      - /Users/jin/Desktop/career/side-projects/docker-volume/event-driven-order-system:/var/lib/postgresql/data
    container_name: event-driven-order-system-db